spring.application.name=java-project
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=JDBC:mysql://localhost:3306/JavaProjectDB
spring.datasource.username=simone_zheng
spring.datasource.password=Sasso123!
# tells Spring Boot which java class to use as the MySql database driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver